#!/bin/bash

set -eo pipefail

[ -z "$1" ] && { echo "must provide path to binary" ; exit 1 ; } || { path=$1 ; bin=$(basename $1) ; }
[ ! -f "$path" ] && { echo "$path doesn't exist" ; exit 1 ; }

[ -z "$(lxc list $bin --format json | jq --arg b "$bin" '.[] | select(.name == $b)')" ] || { echo "$bin already exists, can't init" ; exit 1 ; }
lxc launch images:alpine/3.18 $bin
lxc file push ${path} ${bin}/usr/bin/

lexec() {
  lxc exec $bin -- sh -c "$bin $1"
}

lexec "init test --chain-id test-1 &> /dev/null"
lexec "config keyring-backend test"
lexec "config chain-id test-1"
lexec "keys add test 2> seed.txt"
lexec "add-genesis-account test 1000000000000stake,1000000000000uosmo,1000000000000uatom,1000000000000ujuno --keyring-backend test"
lexec "gentx test 100000000stake --keyring-backend test --chain-id test-1"
lexec "collect-gentxs &> /dev/null"